import { build } from "esbuild";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const entry = path.join(root, "src", "ui", "client", "main.ts");
const target = path.join(root, "src", "ui", "client-bundle.generated.ts");

const banner = [
  "// Generated by scripts/build-client.mjs from src/ui/client/. Do not edit by hand.",
  "// Run `npm run build:client` after changing anything under src/ui/client/.",
  "",
  "/* eslint-disable */",
  "",
].join("\n");

function quote(code) {
  const escaped = code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  return "`" + escaped + "`";
}

async function main() {
  const bundled = await build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    format: "iife",
    globalName: "fookieAnalyze",
    target: "es2022",
    platform: "browser",
    charset: "ascii",
    treeShaking: false,
    legalComments: "none",
    logLevel: "warning",
  });

  const outputs = bundled.outputFiles;
  if (outputs.length !== 1) {
    throw new Error(`expected one bundle, got ${outputs.length}`);
  }
  const code = outputs[0].text.trim();
  if (code.length < 1) {
    throw new Error("the client bundle came out empty");
  }
  if (code.includes("</script")) {
    throw new Error("the client bundle closes its own script tag");
  }

  const written = `${banner}export const clientBundleJs = ${quote(code)};\n`;
  const before = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (before === written) {
    console.log(`client bundle unchanged (${code.length} bytes)`);
    return;
  }
  if (process.argv.includes("--check")) {
    console.error("src/ui/client-bundle.generated.ts is stale. Run: npm run build:client");
    process.exit(1);
  }
  writeFileSync(target, written);
  console.log(`wrote client bundle (${code.length} bytes)`);
}

await main();
