version: '3.8'

services:
  lgtm-stack:
    image: grafana/otel-lgtm
    container_name: lgtm-stack
    ports:
      - "3000:3000"  # Grafana UI
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./data/grafana:/data/grafana
      - ./data/prometheus:/data/prometheus
      - ./data/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - otel-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config:/etc/loki
    networks:
      - otel-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - otel-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


networks:
  otel-net:
    driver: bridge