sonar.projectKey=fookiejs_core
sonar.organization=fookiejs
sonar.projectName=fookie-core
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/.git/**,**/.github/**,**/.vscode/**,**/.sonarlint/**,**/scripts/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out

sonar.issue.ignore.multicriteria=cc1
sonar.issue.ignore.multicriteria.cc1.ruleKey=go:S3776
sonar.issue.ignore.multicriteria.cc1.resourceKey=**/*
