sonar.projectKey=fookiejs_core
sonar.organization=fookiejs
sonar.projectName=fookie-core
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/.git/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
