// Generated by scripts/build-client.mjs from src/ui/client/. Do not edit by hand.
// Run `npm run build:client` after changing anything under src/ui/client/.

/* eslint-disable */
export const clientBundleJs = `"use strict";
var fookieAnalyze = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/ui/client/main.ts
  var main_exports = {};
  __export(main_exports, {
    compensatedRuns: () => compensatedRuns,
    drawMap: () => drawMap,
    drawRelations: () => drawRelations,
    paint: () => paint,
    renderLogs: () => renderLogs,
    renderOutbox: () => renderOutbox,
    renderRuns: () => renderRuns,
    renderStuck: () => renderStuck,
    show: () => show,
    state: () => state,
    stuckCount: () => stuckCount,
    stuckGroups: () => stuckGroups
  });

  // src/ui/client/card.ts
  function portRow(node, port, at, trail) {
    const y = node.y + CARD_HEADER + at * PORT_ROW;
    const mid = y + PORT_ROW / 2;
    const key = portKey(node.id, port.id);
    let lit = "";
    for (const shown of trail) {
      lit = shown.ports[key] === true ? " lit" : "";
    }
    const row = svgEl("g", { class: "port" + (port.active ? " active" : "") + lit });
    row.appendChild(
      svgEl("rect", {
        class: "hit",
        x: node.x + 1,
        y: y + 1,
        width: node.width - 2,
        height: PORT_ROW - 2,
        rx: "5"
      })
    );
    row.appendChild(svgEl("text", { class: "port-label", x: node.x + 18, y: mid + 4.5 }, port.label));
    if (port.detail) {
      row.appendChild(
        svgEl(
          "text",
          { class: "port-detail", x: node.x + node.width - 18, y: mid + 4.5 },
          port.detail
        )
      );
    }
    if (port.active) {
      row.appendChild(
        svgEl("circle", { class: "port-dot out", cx: node.x + node.width, cy: mid, r: "4" })
      );
    }
    row.appendChild(svgEl("circle", { class: "port-dot in", cx: node.x, cy: mid, r: "4" }));
    row.addEventListener("click", (event) => {
      if (event.button !== 0) {
        return;
      }
      event.stopPropagation();
      selectPort(key);
    });
    return row;
  }
  function fieldRows(node) {
    const rows = [];
    if (node.fields.length === 0) {
      return rows;
    }
    const top = node.y + CARD_HEADER + node.ports.length * PORT_ROW;
    let at = 0;
    if (node.ports.length > 0) {
      const head = svgEl("g", { class: "fields-head" });
      head.appendChild(
        svgEl("line", { class: "divider", x1: node.x, y1: top, x2: node.x + node.width, y2: top })
      );
      head.appendChild(
        svgEl("text", { class: "section-label", x: node.x + 18, y: top + 16 }, "fields")
      );
      rows.push(head);
    } else {
      const head = svgEl("g", { class: "fields-head" });
      head.appendChild(
        svgEl("line", { class: "divider", x1: node.x, y1: top, x2: node.x + node.width, y2: top })
      );
      rows.push(head);
    }
    const bodyTop = node.ports.length > 0 ? top + SECTION_HEAD : top;
    for (const field of node.fields) {
      const y = bodyTop + at * FIELD_ROW;
      const line = svgEl("g", { class: "field" + (field.relation.length > 0 ? " relation" : "") });
      line.appendChild(svgEl("text", { class: "field-key", x: node.x + 18, y: y + 16 }, field.key));
      line.appendChild(
        svgEl(
          "text",
          { class: "field-detail", x: node.x + node.width - 18, y: y + 16 },
          field.detail
        )
      );
      if (field.relation.length > 0) {
        line.appendChild(
          svgEl("circle", {
            class: "port-dot out",
            cx: node.x + node.width,
            cy: y + FIELD_ROW / 2,
            r: "3.5"
          })
        );
      }
      rows.push(line);
      at = at + 1;
    }
    return rows;
  }
  function externalNodeIdOf(name) {
    return "external:" + name;
  }
  function runStatusOf(node) {
    if (!state.selectedRun) {
      return "";
    }
    for (const step of state.runTrail.steps) {
      if (externalNodeIdOf(step.name) !== node.id) {
        continue;
      }
      return step.status;
    }
    if (node.kind === "model") {
      if (node.label !== state.runTrail.model) {
        return "untouched";
      }
      return state.runTrail.phase ? "phase-" + state.runTrail.phase : "";
    }
    return "untouched";
  }
  function statusBadge(node, status) {
    if (!status || status === "untouched") {
      return [];
    }
    const label = status.indexOf("phase-") === 0 ? status.slice(6) : status.replace("_", " ");
    const group = svgEl("g", { class: "run-tag " + status });
    const width = 8 + label.length * 6.2;
    group.appendChild(
      svgEl("rect", {
        class: "run-tag-bg",
        x: node.x + node.width - width - 12,
        y: node.y + 10,
        width,
        height: 17,
        rx: "8"
      })
    );
    group.appendChild(
      svgEl(
        "text",
        { class: "run-tag-text", x: node.x + node.width - width / 2 - 12, y: node.y + 22 },
        label
      )
    );
    return [group];
  }
  function cardFor(node, trail) {
    const dimmed = trail.length > 0 && nodeIsLit(trail, node) === false ? " faded" : "";
    const status = runStatusOf(node);
    const runClass = status ? " run-" + status : "";
    const wrap = svgEl("g", { class: "node " + node.kind + dimmed + runClass });
    wrap.appendChild(
      svgEl("rect", {
        class: "body",
        x: node.x,
        y: node.y,
        width: node.width,
        height: node.height,
        rx: "11"
      })
    );
    wrap.appendChild(svgEl("path", { class: "cap", d: capPath(node) }));
    wrap.appendChild(svgEl("text", { class: "label", x: node.x + 15, y: node.y + 21 }, node.label));
    wrap.appendChild(svgEl("text", { class: "sub", x: node.x + 15, y: node.y + 36 }, node.subtitle));
    let at = 0;
    for (const port of node.ports) {
      wrap.appendChild(portRow(node, port, at, trail));
      at = at + 1;
    }
    for (const row of fieldRows(node)) {
      wrap.appendChild(row);
    }
    for (const tag of statusBadge(node, status)) {
      wrap.appendChild(tag);
    }
    wrap.addEventListener("click", (event) => {
      if (event.button !== 0) {
        return;
      }
      event.stopPropagation();
      selectPort(portKey(node.id, ""));
    });
    return wrap;
  }
  function capPath(node) {
    const x = node.x;
    const y = node.y;
    const w = node.width;
    const r = 11;
    return "M " + x + " " + (y + CARD_HEADER) + " L " + x + " " + (y + r) + " Q " + x + " " + y + " " + (x + r) + " " + y + " L " + (x + w - r) + " " + y + " Q " + (x + w) + " " + y + " " + (x + w) + " " + (y + r) + " L " + (x + w) + " " + (y + CARD_HEADER) + " Z";
  }

  // src/ui/client/detail.ts
  function jsonBlock(value) {
    const box = el("pre", { class: "json" });
    try {
      box.textContent = JSON.stringify(value, (_key, held) => held, 2);
    } catch {
      box.textContent = String(value);
    }
    return box;
  }
  function stepRowsFor(externalId) {
    const found = [];
    for (const row of state.runRows) {
      if (row.externalId === externalId) {
        found.push(row);
      }
    }
    for (const row of state.outbox) {
      if (row.externalId !== externalId) {
        continue;
      }
      let known = false;
      for (const hit of found) {
        if (hit.externalId === externalId) {
          known = true;
        }
      }
      if (known === false) {
        found.push(row);
      }
    }
    return found;
  }
  function spanForExternal(externalId) {
    for (const span of state.obs.spans) {
      const attributes = span.attributes || {};
      if (attributes["externalId"] === externalId) {
        return [span];
      }
    }
    return [];
  }
  function logsForRun(runId) {
    const found = [];
    for (const entry of state.obs.logs) {
      if (entry.traceId !== runId) {
        continue;
      }
      found.push(entry);
    }
    return found.toReversed().slice(0, 20);
  }
  function closeStep() {
    state.selectedStep = "";
    const panel = byId("detail");
    panel.classList.remove("on");
    clear(panel);
  }
  function openStep(externalId) {
    state.selectedStep = externalId;
    renderStepDetail();
  }
  function detailHead(panel, row) {
    const head = el("div", { class: "inspector-head" });
    const grow = el("div", { class: "grow" });
    grow.appendChild(el("h2", {}, row.name));
    grow.appendChild(el("div", { class: "card-desc mono" }, shortId(row.externalId)));
    head.appendChild(grow);
    const close = el("button", { class: "btn icon ghost", title: "Close" }, "\\xD7");
    close.addEventListener("click", () => closeStep());
    head.appendChild(close);
    panel.appendChild(head);
    const chips = el("div", { class: "chips" });
    chips.appendChild(badge(row.status, toneForStatus(row.status)));
    chips.appendChild(badge("attempt " + String(row.attempt), row.attempt > 1 ? "warn" : ""));
    chips.appendChild(badge("step " + String(row.stepIndex), ""));
    if (row.compensationOf && row.compensationOf.length > 0) {
      chips.appendChild(badge("undoes a step", "violet"));
    }
    panel.appendChild(chips);
  }
  function renderStepDetail() {
    const panel = byId("detail");
    if (!panel) {
      return;
    }
    if (state.selectedStep.length < 1) {
      closeStep();
      return;
    }
    const rows = stepRowsFor(state.selectedStep);
    if (rows.length < 1) {
      clear(panel);
      panel.classList.add("on");
      emptyState(
        panel,
        "That step is no longer listed",
        "Fetch the request again to bring its rows back."
      );
      return;
    }
    clear(panel);
    panel.classList.add("on");
    for (const row of rows.slice(0, 1)) {
      detailHead(panel, row);
      if (row.error && row.error.length > 0) {
        panel.appendChild(el("h3", {}, "Why it failed"));
        const reason = el("div", { class: "reason" });
        for (const line of row.error) {
          reason.appendChild(el("div", {}, line));
        }
        panel.appendChild(reason);
      }
      for (const span of spanForExternal(row.externalId)) {
        panel.appendChild(el("h3", {}, "Timing"));
        const kv = el("div", { class: "kv" });
        kv.appendChild(el("div", { class: "k" }, "started"));
        kv.appendChild(el("div", { class: "mono" }, clock(span.startedAt)));
        kv.appendChild(el("div", { class: "k" }, "took"));
        kv.appendChild(el("div", { class: "mono" }, duration(ms(span.startedAt, span.endedAt))));
        panel.appendChild(kv);
      }
      panel.appendChild(el("h3", {}, "Input it was given"));
      panel.appendChild(jsonBlock(row.input));
      if (row.output && row.output.length > 0) {
        panel.appendChild(el("h3", {}, "Output it returned"));
        for (const carried of row.output) {
          panel.appendChild(jsonBlock(carried));
        }
      }
      panel.appendChild(el("h3", {}, "Request"));
      const link = el("div", {});
      link.appendChild(runLink(row.runId));
      panel.appendChild(link);
      const lines = logsForRun(row.runId);
      if (lines.length > 0) {
        panel.appendChild(el("h3", {}, "What the flow logged"));
        for (const entry of lines) {
          const line = el("div", { class: "log-line" });
          line.appendChild(badge(entry.level, toneForLevel(entry.level)));
          line.appendChild(el("span", {}, entry.message));
          panel.appendChild(line);
        }
      }
    }
  }
  function requestBodyOf(runId) {
    for (const run of state.runs) {
      if (run.runId !== runId) {
        continue;
      }
      return [run.body];
    }
    return [];
  }
  function renderRequestDetail(runId) {
    const panel = byId("detail");
    if (!panel) {
      return;
    }
    clear(panel);
    panel.classList.add("on");
    state.selectedStep = "";
    const head = el("div", { class: "inspector-head" });
    const grow = el("div", { class: "grow" });
    grow.appendChild(el("h2", {}, "Request"));
    grow.appendChild(el("div", { class: "card-desc mono" }, shortId(runId)));
    head.appendChild(grow);
    const close = el("button", { class: "btn icon ghost", title: "Close" }, "\\xD7");
    close.addEventListener("click", () => closeStep());
    head.appendChild(close);
    panel.appendChild(head);
    if (state.runTrail.phase) {
      const chips = el("div", { class: "chips" });
      chips.appendChild(badge(state.runTrail.phase, toneForPhase(state.runTrail.phase)));
      if (state.runTrail.model) {
        chips.appendChild(badge(state.runTrail.model, "info"));
      }
      panel.appendChild(chips);
    }
    const bodies = requestBodyOf(runId);
    if (bodies.length > 0) {
      panel.appendChild(el("h3", {}, "What was asked for"));
      for (const body of bodies) {
        panel.appendChild(jsonBlock(body));
      }
    }
    panel.appendChild(el("h3", {}, "Steps"));
    const host = el("div", {});
    tableOf(host, ["External", "Status", "Attempt"], state.runRows, (row) => {
      const line = el("tr", { class: "clickable" });
      cell(line, row.name);
      cell(line, badge(row.status, toneForStatus(row.status)));
      cell(line, String(row.attempt), "num");
      line.addEventListener("click", () => openStep(row.externalId));
      return line;
    });
    panel.appendChild(host);
  }

  // src/ui/client/slot.ts
  function lookup(held, key) {
    if (held.has(key) === false) {
      return [];
    }
    const found = held.get(key);
    if (found === void 0) {
      return [];
    }
    return [found];
  }

  // src/ui/client/stuck.ts
  var deadLetterStatus = "dead_letter";
  function reasonOf(row) {
    if (row.error && row.error.length > 0) {
      return row.error[0] ?? "";
    }
    return "No reason was recorded";
  }
  function groupKeyOf(row) {
    return row.name + " \\u2192 " + reasonOf(row);
  }
  function stuckGroups() {
    const byKey = /* @__PURE__ */ new Map();
    const order = [];
    for (const row of state.outbox) {
      if (row.status !== deadLetterStatus) {
        continue;
      }
      if (matchesSearch([row.name, row.model, reasonOf(row)]) === false) {
        continue;
      }
      const key = groupKeyOf(row);
      if (lookup(byKey, key).length < 1) {
        byKey.set(key, { name: row.name, reason: reasonOf(row), models: [], rows: [] });
        order.push(key);
      }
      for (const group of lookup(byKey, key)) {
        if (group.models.includes(row.model) === false) {
          group.models.push(row.model);
        }
        group.rows.push(row);
      }
    }
    const built = [];
    for (const key of order) {
      for (const group of lookup(byKey, key)) {
        built.push(group);
      }
    }
    return built.toSorted((left, right) => right.rows.length - left.rows.length);
  }
  function compensatedRuns(group) {
    const undone = [];
    for (const row of group.rows) {
      if (rollbackOf(row.runId).length > 0 && undone.includes(row.runId) === false) {
        undone.push(row.runId);
      }
    }
    return undone;
  }
  function rollbackOf(runId) {
    const found = [];
    for (const row of state.outbox) {
      if (row.runId !== runId) {
        continue;
      }
      if (row.compensationOf.length < 1) {
        continue;
      }
      found.push(row);
    }
    return found;
  }
  function stuckHeader(card, group) {
    const head = el("div", { class: "stuck-head" });
    head.appendChild(el("span", { class: "stuck-count" }, String(group.rows.length)));
    const naming = el("div", { class: "stuck-naming" });
    naming.appendChild(el("div", { class: "stuck-name mono" }, group.name));
    naming.appendChild(el("div", { class: "reason" }, group.reason));
    head.appendChild(naming);
    card.appendChild(head);
  }
  function stuckFacts(card, group) {
    const facts = el("div", { class: "stuck-facts" });
    facts.appendChild(el("span", { class: "dim" }, "on " + group.models.join(", ")));
    facts.appendChild(el("span", { class: "dim" }, attemptWording(highestAttempt(group))));
    const undone = compensatedRuns(group);
    if (undone.length === group.rows.length) {
      facts.appendChild(badge("every request rolled back", "ok"));
    }
    if (undone.length > 0 && undone.length < group.rows.length) {
      const left = group.rows.length - undone.length;
      facts.appendChild(badge(String(left) + " left without a rollback", "warn"));
    }
    if (undone.length === 0) {
      facts.appendChild(badge("nothing rolled back", "danger"));
    }
    card.appendChild(facts);
  }
  function attemptWording(attempts) {
    if (attempts === 1) {
      return "gave up on the first attempt";
    }
    return "gave up after " + String(attempts) + " attempts";
  }
  function highestAttempt(group) {
    let highest = 0;
    for (const row of group.rows) {
      if (row.attempt > highest) {
        highest = row.attempt;
      }
    }
    return highest;
  }
  var stuckRunsShown = 8;
  function stuckAffected(card, group) {
    const list = el("div", { class: "stuck-runs" });
    const seen = [];
    for (const row of group.rows) {
      if (seen.length >= stuckRunsShown) {
        break;
      }
      if (seen.includes(row.runId)) {
        continue;
      }
      seen.push(row.runId);
      const line = el("div", { class: "stuck-run" });
      line.appendChild(el("span", { class: "dim mono" }, "step " + String(row.stepIndex)));
      line.appendChild(runLink(row.runId));
      const open = el("button", { class: "btn ghost" }, "why");
      open.addEventListener("click", () => openStep(row.externalId));
      line.appendChild(open);
      list.appendChild(line);
    }
    const hidden = group.rows.length - seen.length;
    if (hidden > 0) {
      list.appendChild(
        el("div", { class: "dim" }, String(hidden) + " more requests hit the same wall")
      );
    }
    card.appendChild(list);
  }
  function renderStuck() {
    const host = byId("stuck-body");
    const groups = stuckGroups();
    if (groups.length === 0 && state.search.length > 0) {
      emptyState(host, "Nothing stuck matches that", "Clear the search to see every dead letter.");
      return;
    }
    if (groups.length === 0) {
      emptyState(
        host,
        "Nothing is stuck",
        "A step lands here once it has exhausted its attempts and stopped retrying."
      );
      return;
    }
    clear(host);
    renderToolbar(host, renderStuck, false);
    for (const group of groups) {
      const card = el("div", { class: "stuck" });
      stuckHeader(card, group);
      stuckFacts(card, group);
      stuckAffected(card, group);
      host.appendChild(card);
    }
  }
  function stuckCount() {
    let total = 0;
    for (const row of state.outbox) {
      if (row.status === deadLetterStatus) {
        total = total + 1;
      }
    }
    return total;
  }

  // src/ui/client/views.ts
  function rootOf(span) {
    return span.parentModel.length === 0;
  }
  function isOperationSpan(span) {
    const attributes = span.attributes || {};
    if (attributes["externalName"]) {
      return false;
    }
    return span.name.indexOf(".") > 0;
  }
  function enclosesBetter(candidate, current) {
    for (const held of current) {
      const a = Date.parse(candidate.startedAt);
      const b = Date.parse(held.startedAt);
      if (a !== b) {
        return a < b;
      }
      return Date.parse(candidate.endedAt) > Date.parse(held.endedAt);
    }
    return true;
  }
  function pickRoot(spans) {
    let root = [];
    for (const span of spans) {
      if (rootOf(span) === false) {
        continue;
      }
      if (isOperationSpan(span) === false) {
        continue;
      }
      if (enclosesBetter(span, root)) {
        root = [span];
      }
    }
    if (root.length > 0) {
      return root;
    }
    for (const span of spans) {
      if (rootOf(span) === false) {
        continue;
      }
      if (enclosesBetter(span, root)) {
        root = [span];
      }
    }
    if (root.length > 0) {
      return root;
    }
    return spans.slice(0, 1);
  }
  function renderToolbar(host, onChange, withTrouble) {
    const bar = el("div", { class: "toolbar" });
    const box = el("input", {
      class: "input",
      id: "search-box",
      placeholder: "Search model, external, message or reason"
    });
    box.value = state.search;
    box.addEventListener("input", (event) => {
      state.search = event.target.value;
      state.page = 0;
      onChange();
    });
    bar.appendChild(box);
    if (withTrouble === false) {
      host.appendChild(bar);
      return;
    }
    const trouble = el("button", { class: "btn" + (state.troubleOnly ? " on" : "") }, "Trouble only");
    trouble.setAttribute("aria-selected", String(state.troubleOnly));
    trouble.addEventListener("click", () => {
      state.troubleOnly = !state.troubleOnly;
      state.page = 0;
      onChange();
    });
    bar.appendChild(trouble);
    host.appendChild(bar);
  }
  function pager(host, shown, total, onChange) {
    const bar = el("div", { class: "pager" });
    const back = el("button", { class: "btn ghost" }, "\\u2190 newer");
    back.disabled = state.page < 1;
    back.addEventListener("click", () => {
      state.page = Math.max(state.page - 1, 0);
      onChange();
    });
    bar.appendChild(back);
    const from = total === 0 ? 0 : state.page * pageSize + 1;
    const to = state.page * pageSize + shown;
    bar.appendChild(el("span", { class: "dim" }, from + "\\u2013" + to + " of " + total));
    const on = el("button", { class: "btn ghost" }, "older \\u2192");
    on.disabled = (state.page + 1) * pageSize >= total;
    on.addEventListener("click", () => {
      state.page = state.page + 1;
      onChange();
    });
    bar.appendChild(on);
    host.appendChild(bar);
  }
  var pageSize = 40;
  function matchesSearch(haystack) {
    const needle = state.search.trim().toLowerCase();
    if (needle.length < 1) {
      return true;
    }
    for (const part of haystack) {
      if (String(part).toLowerCase().includes(needle)) {
        return true;
      }
    }
    return false;
  }
  function troubledOutbox(row) {
    if (row.status === "dead_letter") {
      return true;
    }
    if (row.status === "failed") {
      return true;
    }
    if (row.error && row.error.length > 0) {
      return true;
    }
    if (row.compensationOf && row.compensationOf.length > 0) {
      return true;
    }
    return false;
  }
  function outboxRows() {
    let source = state.outbox;
    if (state.runFilter.length > 0) {
      source = state.runRows.length > 0 ? state.runRows : state.outbox;
    }
    const kept = [];
    for (const row of source) {
      if (state.runFilter.length > 0 && row.runId !== state.runFilter) {
        continue;
      }
      if (state.troubleOnly === true && troubledOutbox(row) === false) {
        continue;
      }
      const reason = row.error && row.error.length > 0 ? row.error[0] ?? "" : "";
      if (matchesSearch([row.name, row.model, row.status, reason]) === false) {
        continue;
      }
      kept.push(row);
    }
    return kept;
  }
  function renderOutbox() {
    const host = byId("outbox-body");
    if (outboxRows().length === 0 && state.runFilter.length > 0) {
      emptyState(
        host,
        "This request called nothing",
        "No external was dispatched for it, so the outbox has nothing to show."
      );
      return;
    }
    if (state.outbox.length === 0) {
      emptyState(
        host,
        "The outbox is empty",
        "Call an external from a flow and every attempt is recorded here."
      );
      return;
    }
    clear(host);
    renderToolbar(host, renderOutbox, true);
    const found = outboxRows();
    const shown = found.slice(state.page * pageSize, state.page * pageSize + pageSize);
    const table = el("div", {});
    host.appendChild(table);
    pager(host, shown.length, found.length, renderOutbox);
    tableOf(table, ["External", "Model", "Status", "Attempt", "Step", "Request"], shown, (row) => {
      const line = el("tr", {});
      cell(line, row.name);
      cell(line, row.model);
      cell(line, badge(row.status, toneForStatus(row.status)));
      cell(line, String(row.attempt), "num");
      cell(line, String(row.stepIndex), "num");
      cell(line, runLink(row.runId));
      line.classList.add("clickable");
      line.addEventListener("click", () => openStep(row.externalId));
      return line;
    });
  }
  function troubledLog(entry) {
    if (entry.level === "error") {
      return true;
    }
    if (entry.level === "warn") {
      return true;
    }
    return false;
  }
  function logRows() {
    const kept = [];
    for (const entry of state.obs.logs.toReversed()) {
      if (state.runFilter.length > 0 && entry.traceId !== state.runFilter) {
        continue;
      }
      if (state.troubleOnly === true && troubledLog(entry) === false) {
        continue;
      }
      if (matchesSearch([entry.message, entry.model, entry.operation, entry.level]) === false) {
        continue;
      }
      kept.push(entry);
    }
    return kept;
  }
  function renderLogs() {
    const host = byId("logs-body");
    const rows = logRows();
    if (rows.length === 0 && state.runFilter.length > 0) {
      emptyState(
        host,
        "Nothing logged for this request",
        "Logs live in memory only, so anything older than the buffer is already gone."
      );
      return;
    }
    if (rows.length === 0) {
      emptyState(host, "No log lines yet", "Anything a flow logs shows up here as it happens.");
      return;
    }
    clear(host);
    renderToolbar(host, renderLogs, true);
    const shown = rows.slice(state.page * pageSize, state.page * pageSize + pageSize);
    const table = el("div", {});
    host.appendChild(table);
    pager(host, shown.length, rows.length, renderLogs);
    tableOf(table, ["", "Time", "Model", "Operation", "Message", "Request"], shown, (entry) => {
      const line = el("tr", {});
      cell(line, badge(entry.level, toneForLevel(entry.level)));
      cell(line, el("span", { class: "dim mono" }, clock(entry.timestamp)));
      cell(line, entry.model);
      cell(line, el("span", { class: "dim" }, entry.operation));
      cell(line, el("span", { class: "truncate" }, entry.message));
      cell(line, runLink(entry.traceId));
      return line;
    });
  }
  var SHAPE_EVERY = 4;
  function shapeIsDue() {
    if (state.catalog.length < 1) {
      return true;
    }
    return state.ticks % SHAPE_EVERY === 0;
  }
  async function refresh() {
    state.ticks = state.ticks + 1;
    const page = await load("/api/obs?since=" + String(state.obsCursor));
    absorb(page);
    if (shapeIsDue()) {
      const [catalog, graph, relations, runs, outbox] = await Promise.all([
        load("/api/catalog"),
        load(graphPath()),
        load(graphPath() + "?plane=data"),
        load("/api/runs?limit=200"),
        load("/api/outbox?limit=300")
      ]);
      state.catalog = catalog.models;
      state.externals = catalog.externals;
      state.graph = graph;
      state.relations = relations;
      state.runs = runs;
      state.outbox = outbox;
    }
    clearFail();
    paint();
  }
  function paint() {
    byId("count-models").textContent = String(state.catalog.length);
    byId("count-models-2").textContent = String(state.catalog.length);
    byId("count-runs").textContent = String(traceGroups().length);
    byId("count-outbox").textContent = String(state.outbox.length);
    byId("count-stuck").textContent = String(stuckCount());
    byId("count-logs").textContent = String(state.obs.logs.length);
    const gap = byId("dropped");
    if (gap) {
      gap.hidden = state.dropped < 1;
      gap.textContent = String(state.dropped) + " entries aged out before you saw them";
    }
    if (state.view === "map") {
      drawMap();
      renderInspector();
    }
    if (state.view === "models") {
      drawRelations();
    }
    if (state.view === "runs") {
      renderRuns();
    }
    if (state.view === "outbox") {
      renderOutbox();
    }
    if (state.view === "stuck") {
      renderStuck();
    }
    if (state.view === "logs") {
      renderLogs();
    }
  }
  var mapTitle = [
    "Flows",
    "What each operation calls, in the order it called it"
  ];
  var titles = {
    map: mapTitle,
    models: ["Relations", "Every model, its columns and what it points at"],
    runs: ["Operations", "Each root operation with the flows it started underneath"],
    outbox: ["Outbox", "One row per external call attempt"],
    stuck: ["Stuck", "Steps that exhausted their attempts, grouped by what stopped them"],
    logs: ["Logs", "Everything the flows emitted"]
  };
  var defaultView = "map";
  function isCanvasView(name) {
    if (name === "map") {
      return true;
    }
    if (name === "models") {
      return true;
    }
    return false;
  }
  function viewFromPath(path) {
    const slug = path.replace(/^\\/+/, "").replace(/\\/+$/, "");
    if (slug.length < 1) {
      return defaultView;
    }
    if (titles[slug] === void 0) {
      return defaultView;
    }
    return slug;
  }
  function show(name) {
    const previous = state.view;
    state.view = name;
    const wanted = name === defaultView ? "/" : "/" + name;
    if (location.pathname !== wanted) {
      history.pushState({}, "", wanted);
    }
    for (const section of document.querySelectorAll("section")) {
      section.hidden = section.id !== "view-" + name;
    }
    for (const button of document.querySelectorAll(".nav button")) {
      button.setAttribute("aria-selected", String(button.dataset["view"] === name));
    }
    renderCrumb();
    const heading = titles[name] || mapTitle;
    byId("view-title").textContent = heading[0];
    byId("view-subtitle").textContent = heading[1];
    state.page = 0;
    byId("content").classList.toggle("flush", isCanvasView(name));
    byId("map-actions").hidden = isCanvasView(name) === false;
    byId("runs-actions").hidden = name !== "runs";
    if (previous !== name) {
      state.camera.ready = false;
    }
    paint();
  }
  function wire() {
    for (const button of document.querySelectorAll(".nav button")) {
      button.addEventListener("click", () => show(button.dataset["view"] ?? ""));
    }
    byId("zoom-in").addEventListener("click", () => {
      zoomCenter(1.2);
    });
    byId("zoom-out").addEventListener("click", () => {
      zoomCenter(1 / 1.2);
    });
    byId("zoom-fit").addEventListener("click", fitMap);
    byId("runs-filter").addEventListener("input", (event) => {
      state.filter = event.target.value;
      renderRuns();
    });
    document.addEventListener("keydown", (event) => {
      if (event.key === "Escape") {
        selectPort("");
      }
      if (event.key === "f" && isCanvasView(state.view) && event.target === document.body) {
        fitMap();
      }
    });
    window.addEventListener("resize", () => {
      if (isCanvasView(state.view) && !state.selectedPort) {
        fitMap();
      }
    });
  }
  function markLive(on) {
    const pulse = byId("pulse");
    pulse.classList.toggle("stale", !on);
    byId("pulse-text").textContent = on ? "live" : "disconnected";
  }
  function wireGate() {
    const form = byId("gate-form");
    if (!form) {
      return;
    }
    form.addEventListener("submit", (event) => {
      event.preventDefault();
      const input = byId("gate-input");
      const offered = input ? input.value.trim() : "";
      if (offered.length < 1) {
        return;
      }
      rememberToken(offered);
      location.replace(location.pathname);
    });
  }

  // src/ui/client/inspector.ts
  function externalNamed(name) {
    for (const external of state.externals) {
      if (external.name === name) {
        return [external];
      }
    }
    return [];
  }
  function metricsForModel(name) {
    const totals = /* @__PURE__ */ new Map();
    const order = [];
    for (const entry of state.obs.metrics) {
      if (entry.model !== name) {
        continue;
      }
      const seen = lookup(totals, entry.name);
      if (seen.length < 1) {
        totals.set(entry.name, entry.value);
        order.push(entry.name);
        continue;
      }
      for (const held of seen) {
        totals.set(entry.name, held + entry.value);
      }
    }
    const built = [];
    for (const key of order) {
      for (const value of lookup(totals, key)) {
        built.push({ name: key, value });
      }
    }
    return built;
  }
  function openFiltered(view, model) {
    state.search = model;
    state.troubleOnly = false;
    state.page = 0;
    state.runFilter = "";
    show(view);
    paint();
  }
  function jumpRow(panel, label, view, model) {
    const row = el("button", { class: "btn ghost jump" }, label);
    row.addEventListener("click", () => openFiltered(view, model));
    panel.appendChild(row);
  }
  function modelActivity(panel, name) {
    const counters = metricsForModel(name);
    panel.appendChild(el("h3", {}, "Counted here"));
    if (counters.length === 0) {
      panel.appendChild(el("div", { class: "dim" }, "Nothing counted yet."));
    }
    for (const counter of counters) {
      const row = el("div", { class: "meter" });
      row.appendChild(el("span", {}, counter.name));
      row.appendChild(el("span", { class: "meter-value mono" }, String(counter.value)));
      panel.appendChild(row);
    }
    panel.appendChild(el("h3", {}, "Look at it in full"));
    panel.appendChild(
      el(
        "div",
        { class: "dim card-desc" },
        "The listings page and filters beat a short list in a side panel."
      )
    );
    jumpRow(panel, "Operations on " + name, "runs", name);
    jumpRow(panel, "Logs from " + name, "logs", name);
    jumpRow(panel, "Outbox for " + name, "outbox", name);
    spanTimes(panel, name);
  }
  function renderInspector() {
    const panel = byId("inspector");
    if (!state.selectedNode) {
      panel.classList.remove("on");
      clear(panel);
      return;
    }
    clear(panel);
    panel.classList.add("on");
    for (const node of lookup(nodesById(), state.selectedNode)) {
      const head = el("div", { class: "inspector-head" });
      const grow = el("div", { class: "grow" });
      grow.appendChild(el("h2", {}, node.label));
      grow.appendChild(el("div", { class: "card-desc mono" }, node.subtitle));
      head.appendChild(grow);
      const close = el("button", { class: "btn icon ghost", title: "Close" }, "\\xD7");
      close.addEventListener("click", () => selectPort(""));
      head.appendChild(close);
      panel.appendChild(head);
      const parts = state.selectedPort.split("#");
      const port = parts.length > 1 ? parts[1] ?? "" : "";
      if (node.kind === "model") {
        inspectModel(panel, node, port);
      } else {
        inspectExternal(panel, node.label);
      }
    }
  }
  function inspectModel(panel, node, port) {
    for (const model of modelNamed(node.label)) {
      panel.appendChild(el("h3", {}, "Flows"));
      for (const flow of node.ports) {
        const row = el("div", { class: "flow-row" + (flow.id === port ? " on" : "") });
        row.appendChild(badge(flow.label, flow.active ? "info" : ""));
        row.appendChild(
          el("span", { class: flow.active ? "" : "dim" }, flow.detail || "calls nothing")
        );
        row.addEventListener("click", () => selectPort(node.id + "#" + flow.id));
        panel.appendChild(row);
      }
      modelActivity(panel, node.label);
      panel.appendChild(el("h3", {}, "Fields"));
      const host = el("div", {});
      tableOf(host, ["Field", "Type", ""], model.fields, (field) => {
        const row = el("tr", {});
        cell(row, field.key);
        cell(row, el("span", { class: "mono dim" }, field.pgType));
        const flags = el("div", { class: "chips" });
        if (field.relation.length > 0) {
          flags.appendChild(badge("\\u2192 " + field.relation[0], "violet"));
        }
        if (field.unique) {
          flags.appendChild(badge("unique", "info"));
        }
        if (field.index && !field.unique) {
          flags.appendChild(badge("index", ""));
        }
        cell(row, flags);
        return row;
      });
      panel.appendChild(host);
    }
  }
  function percentile(sorted, p) {
    if (sorted.length < 1) {
      return 0;
    }
    const rank = Math.ceil(p / 100 * sorted.length) - 1;
    const index = Math.min(sorted.length - 1, Math.max(0, rank));
    const held = sorted[index];
    if (held === void 0) {
      return 0;
    }
    return held;
  }
  function spanTimes(panel, model) {
    const grouped = /* @__PURE__ */ new Map();
    const order = [];
    const needle = model.toLowerCase();
    for (const span of state.obs.spans) {
      const named = span.model === model || span.name.toLowerCase().startsWith(needle + ".");
      if (named === false) {
        continue;
      }
      const took = ms(span.startedAt, span.endedAt);
      const seen = lookup(grouped, span.name);
      if (seen.length < 1) {
        grouped.set(span.name, [took]);
        order.push(span.name);
        continue;
      }
      for (const held of seen) {
        held.push(took);
      }
    }
    panel.appendChild(el("h3", {}, "Span time"));
    if (order.length < 1) {
      panel.appendChild(el("div", { class: "dim" }, "No spans in the live buffer yet."));
      return;
    }
    const host = el("div", {});
    tableOf(host, ["Span", "n", "p50", "p95", "max"], order, (name) => {
      const row = el("tr", {});
      const values = lookup(grouped, name);
      let nums = [];
      for (const held of values) {
        nums = held.slice().sort((a, b) => a - b);
      }
      cell(row, el("span", { class: "mono" }, name));
      cell(row, el("span", { class: "mono" }, String(nums.length)));
      cell(row, el("span", { class: "mono" }, duration(percentile(nums, 50))));
      cell(row, el("span", { class: "mono" }, duration(percentile(nums, 95))));
      cell(row, el("span", { class: "mono" }, duration(percentile(nums, 100))));
      return row;
    });
    panel.appendChild(host);
    panel.appendChild(
      el(
        "div",
        { class: "dim card-desc" },
        "From the in-memory observability buffer. Open Traces for a single request."
      )
    );
  }
  function inspectExternal(panel, name) {
    for (const external of externalNamed(name)) {
      panel.appendChild(el("h3", {}, "Delivery"));
      const kv = el("div", { class: "kv" });
      kv.appendChild(el("div", { class: "k" }, "attempts"));
      kv.appendChild(el("div", {}, String(external.attempts)));
      kv.appendChild(el("div", { class: "k" }, "backoff"));
      kv.appendChild(el("div", {}, external.backoff));
      kv.appendChild(el("div", { class: "k" }, "timeout"));
      kv.appendChild(el("div", {}, external.timeoutMs + "ms"));
      kv.appendChild(el("div", { class: "k" }, "undone by"));
      kv.appendChild(
        el("div", {}, external.compensate.length > 0 ? external.compensate[0] : "nothing")
      );
      panel.appendChild(kv);
      panel.appendChild(el("h3", {}, "Payload"));
      const chips = el("div", { class: "chips" });
      for (const key of external.inputKeys) {
        chips.appendChild(badge("in " + key, "info"));
      }
      for (const key of external.outputKeys) {
        chips.appendChild(badge("out " + key, "ok"));
      }
      panel.appendChild(chips);
      panel.appendChild(el("h3", {}, "Traffic"));
      const counts = outboxCountsFor(name);
      const traffic = el("div", { class: "chips" });
      const entries = Object.entries(counts);
      if (entries.length === 0) {
        traffic.appendChild(el("span", { class: "dim" }, "No calls recorded yet."));
      }
      for (const [key, total] of entries) {
        traffic.appendChild(badge(key + " " + total, toneForStatus(key)));
      }
      panel.appendChild(traffic);
    }
  }
  function outboxCountsFor(name) {
    const counts = /* @__PURE__ */ new Map();
    for (const row of state.outbox) {
      if (row.name !== name) {
        continue;
      }
      let total = 0;
      for (const held of lookup(counts, row.status)) {
        total = held;
      }
      counts.set(row.status, total + 1);
    }
    return counts;
  }

  // src/ui/client/map.ts
  var MIN_ZOOM = 0.2;
  var MAX_ZOOM = 2.6;
  var CARD_HEADER = 58;
  var PORT_ROW = 34;
  var SECTION_HEAD = 24;
  var FIELD_ROW = 24;
  var activeSurface = { svg: [] };
  function surfaceSvg() {
    return activeSurface.svg;
  }
  function surfaceViewport() {
    for (const svg of surfaceSvg()) {
      const group = svg.querySelector("g.viewport");
      if (group instanceof SVGGElement) {
        return [group];
      }
    }
    return [];
  }
  function applyCamera() {
    for (const group of surfaceViewport()) {
      const cam = state.camera;
      group.setAttribute("transform", "translate(" + cam.x + "," + cam.y + ") scale(" + cam.k + ")");
      const readout = byId("zoom-readout");
      if (readout) {
        readout.textContent = Math.round(cam.k * 100) + "%";
      }
      return;
    }
  }
  function zoomAt(clientX, clientY, factor) {
    for (const svg of surfaceSvg()) {
      const box = svg.getBoundingClientRect();
      const px = clientX - box.left;
      const py = clientY - box.top;
      const cam = state.camera;
      const next = Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, cam.k * factor));
      if (next === cam.k) {
        return;
      }
      cam.x = px - (px - cam.x) / cam.k * next;
      cam.y = py - (py - cam.y) / cam.k * next;
      cam.k = next;
      applyCamera();
      return;
    }
  }
  function zoomCenter(factor) {
    for (const svg of surfaceSvg()) {
      const box = svg.getBoundingClientRect();
      if (box.width < 1 || box.height < 1) {
        continue;
      }
      zoomAt(box.left + box.width / 2, box.top + box.height / 2, factor);
      return;
    }
  }
  function fitMap() {
    for (const svg of surfaceSvg()) {
      if (drawnGraph().nodes.length === 0) {
        return;
      }
      const box = svg.getBoundingClientRect();
      if (box.width < 80 || box.height < 80) {
        return;
      }
      const pad = 64;
      const w = drawnGraph().width || 1;
      const h = drawnGraph().height || 1;
      const scale = Math.min((box.width - pad * 2) / w, (box.height - pad * 2) / h, MAX_ZOOM);
      const k = Math.max(MIN_ZOOM, scale);
      state.camera.k = k;
      state.camera.x = (box.width - w * k) / 2;
      state.camera.y = (box.height - h * k) / 2;
      state.camera.ready = true;
      applyCamera();
      return;
    }
  }
  function nodesById() {
    const index = /* @__PURE__ */ new Map();
    for (const node of drawnGraph().nodes) {
      index.set(node.id, node);
    }
    return index;
  }
  function portIndex(node, portId) {
    let at = 0;
    for (const port of node.ports) {
      if (port.id === portId) {
        return at;
      }
      at = at + 1;
    }
    return -1;
  }
  function anchorY(node, portId) {
    const at = portIndex(node, portId);
    if (at >= 0) {
      return node.y + CARD_HEADER + at * PORT_ROW + PORT_ROW / 2;
    }
    let fieldAt = 0;
    for (const field of node.fields) {
      if (field.key === portId) {
        let top = node.y + CARD_HEADER + node.ports.length * PORT_ROW;
        if (node.ports.length > 0) {
          top = top + SECTION_HEAD;
        }
        return top + fieldAt * FIELD_ROW + FIELD_ROW / 2;
      }
      fieldAt = fieldAt + 1;
    }
    return node.y + node.height / 2;
  }
  function edgeAnchors(from, fromPort, to, toPort) {
    const y1 = anchorY(from, fromPort);
    const y2 = anchorY(to, toPort);
    const fromMid = from.x + from.width / 2;
    const toMid = to.x + to.width / 2;
    if (toMid >= fromMid) {
      return { x1: from.x + from.width, y1, x2: to.x, y2 };
    }
    return { x1: from.x, y1, x2: to.x + to.width, y2 };
  }
  function edgePath(from, fromPort, to, toPort) {
    const ends = edgeAnchors(from, fromPort, to, toPort);
    const x1 = ends.x1;
    const y1 = ends.y1;
    const x2 = ends.x2;
    const y2 = ends.y2;
    if (x2 >= x1) {
      const reach = Math.max(40, (x2 - x1) * 0.55);
      return "M " + x1 + " " + y1 + " C " + (x1 + reach) + " " + y1 + ", " + (x2 - reach) + " " + y2 + ", " + x2 + " " + y2;
    }
    const back = Math.max(70, (x1 - x2) / 2);
    const lift = y1 <= y2 ? -Math.max(50, back / 2) : Math.max(50, back / 2);
    return "M " + x1 + " " + y1 + " C " + (x1 + back) + " " + (y1 + lift) + ", " + (x2 - back) + " " + (y2 + lift) + ", " + x2 + " " + y2;
  }
  var flowPlane = "flow";
  var dataPlane = "data";
  var drawnPlane = { name: flowPlane };
  function drawnGraph() {
    return drawnPlane.name === dataPlane ? state.relations : state.graph;
  }
  function visibleEdges() {
    const shown = [];
    for (const edge of drawnGraph().edges) {
      if (drawnPlane.name === flowPlane) {
        if (edge.plane !== flowPlane && edge.kind !== "relation") {
          continue;
        }
      } else if (edge.plane !== drawnPlane.name) {
        continue;
      }
      shown.push(edge);
    }
    return shown;
  }
  function edgeWalkedByRun(edge) {
    if (!state.selectedRun) {
      return true;
    }
    for (const step of state.runTrail.steps) {
      if (edge.to === externalNodeIdOf(step.name)) {
        return true;
      }
    }
    return false;
  }
  function portKey(nodeId, portId) {
    return nodeId + "#" + portId;
  }
  function edgeKey(edge) {
    return edge.from + ">" + edge.fromPort + ">" + edge.to + ">" + edge.toPort;
  }
  function downstreamOf(nodeId, portId) {
    const ports = {};
    const edges = {};
    const root = portKey(nodeId, portId);
    let frontier = [root];
    ports[root] = true;
    let guard = 0;
    while (frontier.length > 0 && guard < 64) {
      guard = guard + 1;
      const next = [];
      for (const edge of visibleEdges()) {
        if (frontier.indexOf(portKey(edge.from, edge.fromPort)) < 0) {
          continue;
        }
        edges[edgeKey(edge)] = true;
        const target = portKey(edge.to, edge.toPort);
        if (ports[target]) {
          continue;
        }
        ports[target] = true;
        next.push(target);
      }
      frontier = next;
    }
    return { ports, edges };
  }
  function relationTrail(nodeId) {
    const ports = {};
    const edges = {};
    ports[portKey(nodeId, "")] = true;
    for (const edge of drawnGraph().edges) {
      if (edge.from !== nodeId && edge.to !== nodeId) {
        continue;
      }
      edges[edgeKey(edge)] = true;
      ports[portKey(edge.from, edge.fromPort)] = true;
      ports[portKey(edge.to, "")] = true;
      ports[portKey(edge.from, "")] = true;
    }
    return { ports, edges };
  }
  function highlight() {
    if (!state.selectedPort) {
      return [];
    }
    const parts = state.selectedPort.split("#");
    const nodeId = parts[0] ?? "";
    if (drawnPlane.name === dataPlane) {
      return [relationTrail(nodeId)];
    }
    return [downstreamOf(nodeId, parts.length > 1 ? parts[1] ?? "" : "")];
  }
  function edgeIsLit(trail, edge) {
    for (const lit of trail) {
      return lit.edges[edgeKey(edge)] === true;
    }
    return false;
  }
  function nodeIsLit(trail, node) {
    for (const lit of trail) {
      if (lit.ports[portKey(node.id, "")] === true) {
        return true;
      }
      for (const port of node.ports) {
        if (lit.ports[portKey(node.id, port.id)] === true) {
          return true;
        }
      }
      for (const field of node.fields) {
        if (lit.ports[portKey(node.id, field.key)] === true) {
          return true;
        }
      }
    }
    return false;
  }
  function markerDefs(defs, plane) {
    for (const kind of ["relation", "invokes", "compensates", "nests"]) {
      const marker = svgEl("marker", {
        id: "arrow-" + kind + "-" + plane,
        viewBox: "0 0 10 10",
        refX: "8",
        refY: "5",
        markerWidth: "5",
        markerHeight: "5",
        orient: "auto-start-reverse"
      });
      marker.appendChild(svgEl("path", { d: "M 0 1 L 9 5 L 0 9 z", class: "arrow " + kind }));
      defs.appendChild(marker);
    }
  }
  function drawMap() {
    drawnPlane.name = flowPlane;
    clear(byId("models-body"));
    drawGraph(byId("map-canvas"), "No models registered");
  }
  function drawRelations() {
    drawnPlane.name = dataPlane;
    clear(byId("map-canvas"));
    drawGraph(byId("models-body"), "No relations declared");
  }
  function wireEdgeRaise(bundle, edgesLayer, viewport) {
    bundle.addEventListener("pointerenter", () => {
      bundle.classList.add("raised");
      viewport.appendChild(bundle);
    });
    bundle.addEventListener("pointerleave", () => {
      bundle.classList.remove("raised");
      edgesLayer.appendChild(bundle);
    });
    bundle.addEventListener("click", (event) => {
      event.stopPropagation();
    });
  }
  function edgeBundle(edge, from, to, trail, edgesLayer, viewport) {
    let cls = "edge " + edge.kind;
    if (trail.length > 0) {
      cls = cls + (edgeIsLit(trail, edge) ? " lit" : " faded");
    }
    if (state.selectedRun && edgeWalkedByRun(edge) === false) {
      cls = cls + " faded";
    }
    const path = edgePath(from, edge.fromPort, to, edge.toPort);
    const bundle = svgEl("g", { class: "edge-hit" });
    bundle.appendChild(
      svgEl("path", {
        class: "edge-hitbox",
        d: path
      })
    );
    bundle.appendChild(
      svgEl("path", {
        class: cls,
        "stroke-width": String(Math.min(1.2 + Math.log(edge.weight + 1) * 0.5, 3)),
        "marker-end": "url(#arrow-" + edge.kind + "-" + drawnPlane.name + ")",
        d: path
      })
    );
    if (edge.label) {
      const x = (from.x + from.width + to.x) / 2;
      const y = (anchorY(from, edge.fromPort) + anchorY(to, edge.toPort)) / 2 - 7;
      let labelCls = "edge-label";
      if (trail.length > 0) {
        labelCls = labelCls + (edgeIsLit(trail, edge) ? " lit" : " faded");
      }
      bundle.appendChild(svgEl("text", { class: labelCls, x, y }, edge.label));
    }
    wireEdgeRaise(bundle, edgesLayer, viewport);
    return bundle;
  }
  function drawGraph(host, emptyTitle) {
    if (!host) {
      return;
    }
    clear(host);
    if (drawnGraph().nodes.length === 0) {
      emptyState(host, emptyTitle, "Boot an app with at least one model and it appears here.");
      return;
    }
    const plane = drawnPlane.name;
    const svg = svgEl("svg", {
      class: "map-surface",
      "data-plane": plane,
      width: "100%",
      height: "100%",
      preserveAspectRatio: "xMidYMid meet"
    });
    const defs = svgEl("defs", {});
    const dotsId = "dots-" + plane;
    const dots = svgEl("pattern", {
      id: dotsId,
      width: "24",
      height: "24",
      patternUnits: "userSpaceOnUse"
    });
    dots.appendChild(svgEl("circle", { cx: "1", cy: "1", r: "1", class: "map-dots" }));
    defs.appendChild(dots);
    markerDefs(defs, plane);
    svg.appendChild(defs);
    svg.appendChild(
      svgEl("rect", {
        class: "map-board",
        x: "0",
        y: "0",
        width: "100%",
        height: "100%",
        fill: "url(#" + dotsId + ")"
      })
    );
    const group = svgEl("g", { class: "viewport" });
    const edgesLayer = svgEl("g", { class: "edges" });
    const nodesLayer = svgEl("g", { class: "nodes" });
    const index = nodesById();
    const trail = highlight();
    for (const edge of visibleEdges()) {
      for (const from of lookup(index, edge.from)) {
        for (const to of lookup(index, edge.to)) {
          edgesLayer.appendChild(edgeBundle(edge, from, to, trail, edgesLayer, group));
        }
      }
    }
    for (const node of drawnGraph().nodes) {
      nodesLayer.appendChild(cardFor(node, trail));
    }
    group.appendChild(edgesLayer);
    group.appendChild(nodesLayer);
    svg.appendChild(group);
    svg.addEventListener("click", () => selectPort(""));
    host.appendChild(svg);
    activeSurface.svg = [svg];
    wireCamera(svg);
    let settleTries = 0;
    const settleCamera = () => {
      if (state.camera.ready) {
        applyCamera();
        return;
      }
      fitMap();
      settleTries = settleTries + 1;
      if (state.camera.ready || settleTries > 30) {
        applyCamera();
        return;
      }
      requestAnimationFrame(settleCamera);
    };
    requestAnimationFrame(settleCamera);
  }
  function wireCamera(svg) {
    const drag = { pan: false, zoom: false, x: 0, y: 0, originY: 0, originK: 1 };
    svg.addEventListener(
      "wheel",
      (event) => {
        event.preventDefault();
        zoomAt(event.clientX, event.clientY, Math.exp(-event.deltaY * 1e-3));
      },
      { passive: false }
    );
    svg.addEventListener("contextmenu", (event) => event.preventDefault());
    svg.addEventListener("pointerdown", (event) => {
      if (event.button === 0) {
        const target = event.target;
        if (target instanceof Element && target.classList.contains("map-board") === false) {
          return;
        }
        event.preventDefault();
        drag.pan = true;
        drag.x = event.clientX - state.camera.x;
        drag.y = event.clientY - state.camera.y;
        svg.classList.add("dragging");
        svg.setPointerCapture(event.pointerId);
        return;
      }
      if (event.button === 2) {
        event.preventDefault();
        drag.zoom = true;
        drag.originY = event.clientY;
        drag.originK = state.camera.k;
        svg.setPointerCapture(event.pointerId);
      }
    });
    svg.addEventListener("pointermove", (event) => {
      if (drag.pan) {
        state.camera.x = event.clientX - drag.x;
        state.camera.y = event.clientY - drag.y;
        applyCamera();
        return;
      }
      if (drag.zoom) {
        const next = drag.originK * Math.exp(-(event.clientY - drag.originY) * 3e-3);
        zoomAt(event.clientX, event.clientY, next / state.camera.k);
      }
    });
    const stop = (event) => {
      drag.pan = false;
      drag.zoom = false;
      svg.classList.remove("dragging");
      if (svg.hasPointerCapture(event.pointerId)) {
        svg.releasePointerCapture(event.pointerId);
      }
    };
    svg.addEventListener("pointerup", stop);
    svg.addEventListener("pointercancel", stop);
  }
  function modelNamed(name) {
    for (const model of state.catalog) {
      if (model.name === name) {
        return [model];
      }
    }
    return [];
  }
  function selectPort(key) {
    state.selectedPort = key === state.selectedPort ? "" : key;
    state.selectedNode = state.selectedPort ? state.selectedPort.split("#")[0] ?? "" : "";
    if (state.view === "models") {
      drawRelations();
    } else {
      drawMap();
    }
    renderInspector();
  }
  function runCountFor(model) {
    let total = 0;
    for (const run of state.runs) {
      if (run.model === model) {
        total = total + 1;
      }
    }
    return total;
  }

  // src/ui/client/trace.ts
  function startsAt(span) {
    return Date.parse(span.startedAt);
  }
  function endsAt(span) {
    return Date.parse(span.endedAt);
  }
  function contains(outer, inner) {
    if (outer === inner) {
      return false;
    }
    const from = startsAt(outer);
    const to = endsAt(outer);
    const a = startsAt(inner);
    const b = endsAt(inner);
    if (!isFinite(from) || !isFinite(a)) {
      return false;
    }
    return from <= a && b <= to;
  }
  function traceGroups() {
    const order = [];
    const groups = /* @__PURE__ */ new Map();
    for (const span of state.obs.spans) {
      const known = lookup(groups, span.traceId);
      if (known.length < 1) {
        groups.set(span.traceId, { traceId: span.traceId, spans: [span], root: [] });
        order.push(span.traceId);
        continue;
      }
      for (const group of known) {
        group.spans.push(span);
      }
    }
    const built = [];
    for (const traceId of order) {
      for (const group of lookup(groups, traceId)) {
        group.root = pickRoot(group.spans);
        built.push(group);
      }
    }
    return built.toReversed();
  }
  function passesOf(group) {
    const root = group.root;
    const passes = [];
    for (const held of root) {
      for (const span of group.spans) {
        if (isOperationSpan(span) === false) {
          continue;
        }
        if (span.model !== held.model) {
          continue;
        }
        if (span.entityId !== held.entityId) {
          continue;
        }
        if (span.name !== held.name) {
          continue;
        }
        passes.push(span);
      }
    }
    return passes.toSorted((left, right) => startsAt(left) - startsAt(right));
  }
  function operationSpansOf(group) {
    const spans = [];
    for (const span of group.spans) {
      if (isOperationSpan(span)) {
        spans.push(span);
      }
    }
    return spans;
  }
  function innermostContainer(span, candidates) {
    let best = [];
    for (const candidate of candidates) {
      if (contains(candidate, span) === false) {
        continue;
      }
      if (tighterThan(candidate, best)) {
        best = [candidate];
      }
    }
    return best;
  }
  function tighterThan(candidate, best) {
    for (const held of best) {
      return endsAt(candidate) - startsAt(candidate) < endsAt(held) - startsAt(held);
    }
    return true;
  }
  function namedParent(group, span) {
    if (span.parentModel.length === 0) {
      return [];
    }
    let best = [];
    for (const candidate of operationSpansOf(group)) {
      if (candidate === span) {
        continue;
      }
      if (candidate.model !== span.parentModel[0]) {
        continue;
      }
      if (candidate.entityId !== span.parentEntityId[0]) {
        continue;
      }
      if (contains(candidate, span) === false) {
        continue;
      }
      if (tighterThan(candidate, best)) {
        best = [candidate];
      }
    }
    return best;
  }
  function sortChildren(node) {
    node.children = node.children.toSorted(
      (left, right) => startsAt(left.span) - startsAt(right.span)
    );
    for (const child of node.children) {
      sortChildren(child);
    }
  }
  function buildTree(group) {
    const passes = passesOf(group);
    const operations = operationSpansOf(group);
    const nodes = /* @__PURE__ */ new Map();
    for (const span of group.spans) {
      nodes.set(span.seq, { span, children: [] });
    }
    const loose = [];
    for (const span of group.spans) {
      if (passes.includes(span)) {
        continue;
      }
      const named = namedParent(group, span);
      const parent = named.length > 0 ? named : innermostContainer(span, operations);
      for (const own of lookup(nodes, span.seq)) {
        let placed = false;
        for (const holder of parent) {
          for (const kept of lookup(nodes, holder.seq)) {
            kept.children.push(own);
            placed = true;
          }
        }
        if (placed === false) {
          loose.push(own);
        }
      }
    }
    const ordered = [];
    for (const pass of passes) {
      for (const node of lookup(nodes, pass.seq)) {
        ordered.push(node);
      }
    }
    for (const node of ordered) {
      sortChildren(node);
    }
    for (const node of loose) {
      sortChildren(node);
    }
    return {
      passes: ordered,
      loose: loose.toSorted((l, r) => startsAt(l.span) - startsAt(r.span))
    };
  }
  function sourceOf(group) {
    let attributes = {};
    let rootModel = "";
    for (const held of group.root) {
      attributes = held.attributes;
      rootModel = held.model;
    }
    const named = attributes["source"];
    if (named === "http") {
      return { text: "http request", tone: "info" };
    }
    if (named === "graphql") {
      return { text: "graphql", tone: "violet" };
    }
    if (named === "dispatcher") {
      return { text: "outbox dispatcher", tone: "warn" };
    }
    if (named === "boot") {
      return { text: "boot", tone: "" };
    }
    if (rootModel === "dispatcher") {
      return { text: "outbox dispatcher", tone: "warn" };
    }
    return { text: "direct call", tone: "" };
  }
  function signalOf(span) {
    const attributes = span.attributes || {};
    return attributes["signal"] || "";
  }
  function toneForSignal(signal) {
    if (signal === "done") {
      return "ok";
    }
    if (signal === "failed") {
      return "bad";
    }
    if (signal === "running") {
      return "warn";
    }
    return "";
  }
  function runFor(traceId) {
    for (const run of state.runs) {
      if (run.runId === traceId) {
        return [run];
      }
    }
    return [];
  }
  function stepRow(node, depth, span0, total, label) {
    const span = node.span;
    const rows = [];
    const line = el("div", { class: "step" });
    line.appendChild(el("span", { class: "rail" }));
    line.appendChild(el("span", { class: "tick" }));
    line.appendChild(el("span", { style: "width:" + depth * 18 + "px" }));
    if (label) {
      line.appendChild(badge(label, ""));
    }
    line.appendChild(el("span", { class: "name" }, span.name));
    const signal = signalOf(span);
    if (signal) {
      line.appendChild(badge(signal, toneForSignal(signal)));
    }
    line.appendChild(el("span", { class: "grow" }));
    const took = ms(span.startedAt, span.endedAt);
    const track = el("div", { class: "bar-track" });
    const width = total > 0 ? Math.max(took / total * 100, 1.2) : 100;
    const started = startsAt(span);
    const offset = total > 0 && isFinite(started) ? (started - span0) / total * 100 : 0;
    const tone = signal === "failed" ? "bad" : signal === "done" ? "ok" : "warn";
    const bar = el("div", { class: "bar " + tone });
    bar.setAttribute(
      "style",
      "left:" + Math.max(Math.min(offset, 99), 0) + "%;width:" + Math.min(width, 100) + "%"
    );
    track.appendChild(bar);
    line.appendChild(track);
    line.appendChild(el("span", { class: "meta dim mono" }, duration(took)));
    const attributes = span.attributes || {};
    const externalId = attributes["externalId"];
    if (externalId) {
      line.classList.add("openable");
      line.addEventListener("click", () => openStep(externalId));
    }
    rows.push(line);
    for (const child of node.children) {
      for (const nested of stepRow(child, depth + 1, span0, total, "")) {
        rows.push(nested);
      }
    }
    return rows;
  }
  function renderTrace(host, group) {
    const wrap = el("div", { class: "trace" });
    const head = el("button", {
      class: "trace-head",
      "aria-expanded": state.openTraces[group.traceId] ? "true" : "false"
    });
    head.appendChild(el("span", { class: "caret" }, "\\u25B6"));
    const source = sourceOf(group);
    head.appendChild(badge(source.text, source.tone));
    let who = group.traceId;
    for (const held of group.root) {
      who = held.name;
    }
    head.appendChild(el("span", { class: "who" }, who));
    for (const run of runFor(group.traceId)) {
      head.appendChild(badge(run.phase, toneForPhase(run.phase)));
    }
    head.appendChild(el("span", { class: "grow" }));
    head.appendChild(
      el(
        "span",
        { class: "meta" },
        passesOf(group).length + " passes, " + group.spans.length + " spans"
      )
    );
    head.appendChild(runLink(group.traceId));
    const body = el("div", {
      class: "trace-body" + (state.openTraces[group.traceId] ? " on" : "")
    });
    head.addEventListener("click", () => {
      const open = !state.openTraces[group.traceId];
      state.openTraces[group.traceId] = open;
      head.setAttribute("aria-expanded", open ? "true" : "false");
      body.classList.toggle("on", open);
    });
    let earliest = Number.MAX_SAFE_INTEGER;
    let latest = 0;
    for (const span of group.spans) {
      const from = Date.parse(span.startedAt);
      const to = Date.parse(span.endedAt);
      if (isFinite(from) && from < earliest) {
        earliest = from;
      }
      if (isFinite(to) && to > latest) {
        latest = to;
      }
    }
    const total = Math.max(latest - earliest, 1);
    const tree = buildTree(group);
    let passNumber = 0;
    for (const pass of tree.passes) {
      passNumber = passNumber + 1;
      const label = tree.passes.length > 1 ? "pass " + passNumber : "";
      for (const line of stepRow(pass, 0, earliest, total, label)) {
        body.appendChild(line);
      }
    }
    for (const orphan of tree.loose) {
      for (const line of stepRow(orphan, 0, earliest, total, "dispatcher")) {
        body.appendChild(line);
      }
    }
    wrap.appendChild(head);
    wrap.appendChild(body);
    host.appendChild(wrap);
  }
  function matchesFilter(group) {
    const needle = state.filter.trim().toLowerCase();
    if (needle.length === 0) {
      return true;
    }
    if (group.traceId.toLowerCase().includes(needle)) {
      return true;
    }
    for (const span of group.spans) {
      if (span.name.toLowerCase().includes(needle)) {
        return true;
      }
      if (span.model.toLowerCase().includes(needle)) {
        return true;
      }
    }
    return false;
  }
  function renderRuns() {
    const host = byId("runs-body");
    const groups = traceGroups().filter(matchesFilter);
    if (groups.length === 0) {
      emptyState(
        host,
        "No operations recorded",
        "Send a request through the app and its whole tree lands here."
      );
      return;
    }
    clear(host);
    for (const group of groups.slice(0, 120)) {
      renderTrace(host, group);
    }
  }
  async function openRequest(runId) {
    state.runFilter = runId;
    show("map");
    await selectRun(runId);
    state.camera.ready = false;
    drawMap();
    fitMap();
  }
  function clearRunFilter() {
    state.runFilter = "";
    state.selectedRun = "";
    state.runTrail = { steps: [], phase: "", waiting: [], model: "" };
    state.runRows = [];
    closeStep();
    renderCrumb();
    paint();
  }
  function renderCrumb() {
    const crumb = byId("crumb");
    if (!crumb) {
      return;
    }
    clear(crumb);
    if (state.selectedRun.length < 1) {
      crumb.hidden = true;
      return;
    }
    crumb.hidden = false;
    crumb.appendChild(el("span", { class: "crumb-label" }, "following"));
    crumb.appendChild(el("span", { class: "mono" }, shortId(state.selectedRun)));
    if (state.runTrail.phase) {
      crumb.appendChild(badge(state.runTrail.phase, toneForPhase(state.runTrail.phase)));
    }
    for (const target of ["map", "runs", "outbox", "logs"]) {
      const wording = target === "runs" ? "operations" : target;
      const jump = el("button", { class: "btn ghost" }, wording);
      jump.addEventListener("click", () => show(target));
      crumb.appendChild(jump);
    }
    const drop = el("button", { class: "btn ghost" }, "clear");
    drop.addEventListener("click", () => clearRunFilter());
    crumb.appendChild(drop);
  }
  async function selectRun(runId) {
    state.selectedRun = runId === state.selectedRun ? "" : runId;
    if (state.selectedRun.length < 1) {
      state.runTrail = { steps: [], phase: "", waiting: [], model: "" };
      state.runRows = [];
      drawMap();
      return;
    }
    const rows = await load(
      "/api/outbox?limit=200&runId=" + encodeURIComponent(state.selectedRun)
    );
    state.runRows = rows;
    const steps = [];
    const waiting = [];
    for (const row of rows) {
      steps.push({ name: row.name, status: row.status, stepIndex: row.stepIndex });
      if (row.status === "pending") {
        waiting.push(row.name);
      }
    }
    let phase = "";
    let model = "";
    for (const run of state.runs) {
      if (run.runId !== state.selectedRun) {
        continue;
      }
      phase = run.phase;
      model = run.model;
    }
    if (model.length < 1) {
      for (const entry of rows) {
        model = entry.model;
      }
    }
    state.runTrail = { steps, phase, waiting, model };
    state.runFilter = state.selectedRun;
    renderCrumb();
    renderRequestDetail(state.selectedRun);
    drawMap();
  }
  function graphPath() {
    return "/api/graph";
  }

  // src/ui/client/core.ts
  var TOKEN_KEY = "fookie-analyze-token";
  function rememberToken(value) {
    try {
      sessionStorage.setItem(TOKEN_KEY, value);
    } catch {
    }
  }
  function forgetToken() {
    try {
      sessionStorage.removeItem(TOKEN_KEY);
    } catch {
    }
  }
  function resolveToken() {
    const fromUrl = new URLSearchParams(location.search).get("token");
    if (fromUrl) {
      rememberToken(fromUrl);
      history.replaceState({}, "", location.pathname);
      return fromUrl;
    }
    try {
      return sessionStorage.getItem(TOKEN_KEY) || "";
    } catch {
      return "";
    }
  }
  var token = resolveToken();
  var NS = "http://www.w3.org/2000/svg";
  var state = {
    view: "map",
    catalog: [],
    externals: [],
    graph: { nodes: [], edges: [], width: 0, height: 0 },
    relations: { nodes: [], edges: [], width: 0, height: 0 },
    runs: [],
    outbox: [],
    obs: { logs: [], metrics: [], spans: [], nextSeq: 0, oldestSeq: 0 },
    obsCursor: 0,
    dropped: 0,
    ticks: 0,
    selectedRun: "",
    runTrail: { steps: [], phase: "", waiting: [], model: "" },
    runRows: [],
    selectedStep: "",
    selectedNode: "",
    selectedPort: "",
    selectedModel: "",
    focus: "",
    openTraces: {},
    filter: "",
    runFilter: "",
    lastTick: 0,
    search: "",
    troubleOnly: false,
    page: 0,
    camera: { x: 40, y: 40, k: 1, ready: false }
  };
  async function load(path) {
    const res = await fetch(path, { headers: { "x-analyze-token": token } });
    if (res.status === 401) {
      forgetToken();
      askForToken();
      throw new Error("this dashboard needs its access token");
    }
    if (!res.ok) {
      throw new Error(path + " answered " + res.status);
    }
    return await res.json();
  }
  function askForToken() {
    const gate = byId("gate");
    if (!gate) {
      return;
    }
    gate.classList.add("on");
    const input = byId("gate-input");
    if (input) {
      input.focus();
    }
  }
  function el(tag, attrs, text = "") {
    const node = document.createElement(tag);
    for (const [key, value] of Object.entries(attrs)) {
      if (key === "class") {
        node.className = String(value);
        continue;
      }
      node.setAttribute(key, String(value));
    }
    node.textContent = String(text);
    return node;
  }
  function svgEl(tag, attrs, text = "") {
    const node = document.createElementNS(NS, tag);
    for (const [key, value] of Object.entries(attrs)) {
      node.setAttribute(key, String(value));
    }
    node.textContent = String(text);
    return node;
  }
  function clear(host) {
    host.replaceChildren();
    return host;
  }
  function byId(id) {
    return document.getElementById(id);
  }
  function shortId(value) {
    const text = String(value || "");
    if (text.length <= 10) {
      return text;
    }
    return text.slice(0, 8) + "\\u2026" + text.slice(-4);
  }
  function ms(from, to) {
    const a = Date.parse(from);
    const b = Date.parse(to);
    if (!isFinite(a) || !isFinite(b)) {
      return 0;
    }
    return Math.max(b - a, 0);
  }
  function duration(value) {
    if (value < 1) {
      return "<1ms";
    }
    if (value < 1e3) {
      return Math.round(value) + "ms";
    }
    return (value / 1e3).toFixed(2) + "s";
  }
  function clock(value) {
    const parsed = Date.parse(value);
    if (!isFinite(parsed)) {
      return "";
    }
    return new Date(parsed).toLocaleTimeString();
  }
  function badge(text, tone) {
    const node = el("span", { class: "badge " + (tone || "") });
    node.appendChild(el("span", { class: "dot" }));
    node.appendChild(document.createTextNode(text));
    return node;
  }
  function toneForPhase(phase) {
    if (phase === "completed") {
      return "ok";
    }
    if (phase === "compensated") {
      return "violet";
    }
    if (phase === "compensating") {
      return "warn";
    }
    if (phase === "stuck") {
      return "bad";
    }
    return "info";
  }
  function toneForStatus(status) {
    if (status === "completed") {
      return "ok";
    }
    if (status === "pending") {
      return "info";
    }
    if (status === "failed") {
      return "warn";
    }
    return "bad";
  }
  function toneForLevel(level) {
    if (level === "error") {
      return "bad";
    }
    if (level === "warn") {
      return "warn";
    }
    return "";
  }
  function emptyState(host, title, hint) {
    const box = el("div", { class: "empty" });
    box.appendChild(el("div", { class: "big" }, title));
    box.appendChild(el("div", {}, hint));
    clear(host).appendChild(box);
  }
  function tableOf(host, columns, rows, render) {
    clear(host);
    const table = el("table", {});
    const head = el("thead", {});
    const headRow = el("tr", {});
    for (const column of columns) {
      headRow.appendChild(el("th", {}, column));
    }
    head.appendChild(headRow);
    table.appendChild(head);
    const body = el("tbody", {});
    for (const row of rows) {
      body.appendChild(render(row));
    }
    table.appendChild(body);
    host.appendChild(table);
  }
  function cell(row, value, cls) {
    const td = el("td", cls ? { class: cls } : {});
    if (value instanceof Node) {
      td.appendChild(value);
    } else {
      td.textContent = String(value);
    }
    row.appendChild(td);
    return td;
  }
  function fail(err) {
    const banner = byId("banner");
    banner.textContent = err instanceof Error && err.message ? err.message : String(err);
    banner.classList.add("on");
  }
  function clearFail() {
    byId("banner").classList.remove("on");
  }
  function looksLikeRunId(value) {
    return /^[0-9a-f]{8}-[0-9a-f]{4}-/.test(String(value));
  }
  function runLink(runId, label) {
    if (looksLikeRunId(runId) === false) {
      return el("span", { class: "mono dim" }, label ? label : String(runId));
    }
    const shown = label ? label : shortId(runId);
    const link = el("button", { class: "run-link", title: "Follow this request" }, shown);
    link.addEventListener("click", (event) => {
      event.stopPropagation();
      openRequest(runId).catch(fail);
    });
    return link;
  }
  var KEPT_ENTRIES = 4e3;
  function keepLast(existing, arriving) {
    if (arriving.length === 0) {
      return existing;
    }
    const merged = existing.concat(arriving);
    if (merged.length <= KEPT_ENTRIES) {
      return merged;
    }
    return merged.slice(merged.length - KEPT_ENTRIES);
  }
  function absorb(page) {
    const missed = state.obsCursor > 0 && page.oldestSeq > state.obsCursor + 1 ? page.oldestSeq - state.obsCursor - 1 : 0;
    if (missed > 0) {
      state.dropped = state.dropped + missed;
    }
    state.obs = {
      logs: keepLast(state.obs.logs, page.logs),
      metrics: keepLast(state.obs.metrics, page.metrics),
      spans: keepLast(state.obs.spans, page.spans),
      nextSeq: page.nextSeq,
      oldestSeq: page.oldestSeq
    };
    state.obsCursor = page.nextSeq;
    return missed;
  }

  // src/ui/client/main.ts
  wire();
  wireGate();
  show(viewFromPath(location.pathname));
  window.addEventListener("popstate", () => show(viewFromPath(location.pathname)));
  if (token) {
    refresh().catch(fail);
  } else {
    askForToken();
  }
  var stream = new EventSource(
    "/api/stream" + (token ? "?token=" + encodeURIComponent(token) : "")
  );
  stream.addEventListener("open", () => {
    markLive(true);
    refresh().catch(fail);
  });
  stream.addEventListener("error", () => markLive(false));
  stream.addEventListener("tick", () => {
    state.lastTick = Date.now();
    refresh().catch(fail);
  });
  var heartbeatMs = 5e3;
  setInterval(() => {
    if (!token) {
      return;
    }
    const quiet = Date.now() - state.lastTick;
    if (quiet < heartbeatMs) {
      return;
    }
    refresh().then(() => {
      state.lastTick = Date.now();
      markLive(true);
    }).catch(fail);
  }, heartbeatMs);
  return __toCommonJS(main_exports);
})();`;
