name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Bu izinler, OIDC token'ı oluşturmak için gereklidir
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Check code
        run: deno task check

      - name: Run tests
        run: deno task test

  publish:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup JSR
        run: deno install -A jsr@$VERSION
        env:
          VERSION: 0.9.1

      - name: Publish to JSR
        run: |
          cd packages/core && jsr publish
          cd ../graphql && jsr publish
          cd ../randomize && jsr publish
          cd ../cache && jsr publish
