name: PR Package Labels

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Tüm commit geçmişini çekmek için

      - name: Check Changed Packages
        id: changed-packages
        run: |
          # PR'da değişen dosyaları al
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main..HEAD)

          # Her paket için değişiklik olup olmadığını kontrol et
          if echo "$CHANGED_FILES" | grep -q "packages/core/"; then
            echo "core=true" >> $GITHUB_OUTPUT
          else
            echo "core=false" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -q "packages/graphql/"; then
            echo "graphql=true" >> $GITHUB_OUTPUT
          else
            echo "graphql=false" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -q "packages/randomize/"; then
            echo "randomize=true" >> $GITHUB_OUTPUT
          else
            echo "randomize=false" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -q "packages/cache/"; then
            echo "cache=true" >> $GITHUB_OUTPUT
          else
            echo "cache=false" >> $GITHUB_OUTPUT
          fi

          # Değişen dosyaları ekrana yazdır (debug için)
          echo "Changed files:"
          echo "$CHANGED_FILES"

      - name: Add Core Label
        if: steps.changed-packages.outputs.core == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['package: core']
            })

      - name: Add GraphQL Label
        if: steps.changed-packages.outputs.graphql == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['package: graphql']
            })

      - name: Add Randomize Label
        if: steps.changed-packages.outputs.randomize == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['package: randomize']
            })

      - name: Add Cache Label
        if: steps.changed-packages.outputs.cache == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['package: cache']
            })
